version: '3.8'

services:
  server:
    image: terraria-server:latest
    build:
      context: .
      args: 
        - SERVER_FILE=${SERVER_FILE}
    ports:
      - 7777:7777/tcp
      - 7778:7778/tcp
      - 7779:7779/tcp
    tty: true
    stdin_open: true
    restart: unless-stopped
    user: terraria:terraria
    volumes:
     - ./data:/home/terraria/.local/share/Terraria
     - ./scripts:/home/terraria/scripts
